### PR TITLE
Fix parameter numbering with whereIn and nested where

### PR DESCRIPTION
**Pull request by jessarcher**
This PR fixes a bug when using a `whereIn` query combined with a `where` query.

Take the following query:

```php
DB::table('my-table')
    ->where('column1', 1)
    ->whereIn('column2', ['foo', 'bar'])
    ->get();
```

Currently, the SQL will be generated as:

```sql
select * from "my-table" where "column1" = :0 and "column2" in (:0, :1)
```

Notice how the parameters in the `in()` clause start at `:0` instead of `:1`.

A similar issue happens when switching the order of the `where` and `whereIn`:

```php
DB::table('my-table')
    ->whereIn('column2', ['foo', 'bar'])
    ->where('column1', 1)
    ->get();
```

```sql
select * from "my-table" where "column2" in (:0, :1) and "column1" = :0
```

In this example, the `column` condition is using `:0` instead of `:2`.

This is because the `whereIn` method is currently working in isolation from the query bindings, and will only work when there are no other bindings in the query.

This PR solves this issue by removing the custom implementation of the `parameterize` method and using the parent implementation instead.

This results in the following SQL for the above two queries:

```sql
select * from "my-table" where "column1" = :0 and "column2" in (:1, :2)
```

```sql
select * from "my-table" where "column2" in (:0, :1) and "column1" = :2
```

I'm assuming there was a reason why the `parameterize` method was customized but I'm not sure what it was or whether it's still relevant. I couldn't get the tests running locally to check for any regressions.

### CODE REVIEW

**Comment by glushkovds** [comment]
Hi @jessarcher 

Thank you for your PR, but this breaks the library's work.

Check out my solution https://github.com/glushkovds/phpclickhouse-laravel/blob/master/docs/known_issues.md#parameter-numbering-with-wherein  

You will most likely have to make some additional changes to your project code, but I haven't found a better solution.

**Comment by jessarcher** [comment]
Hey @glushkovds

Thanks for the reply and solution!

I'm curious to know how this breaks the library though, as I couldn't find any scenarios in my own code where this broke anything. The `#@?` string still gets replaced with the correct parameters.

I also ran into another related issue where the parameter numbering is broken when a where is combined with a nested where. E.g:

```php
DB::table('my-table')
    ->where('column1', 'foo')
    ->where(fn ($query) => $query->where('column2', 'bar'))
    ->get();
```

This one is caused by the `compileWheres` override:

https://github.com/glushkovds/phpclickhouse-laravel/blob/2009960f896851d1baa27422843a799644aeb6b1/src/QueryGrammar.php#L32-L35

The `prepareParameters` method gets called on the nested where, and then gets called again on the whole query in the `Connection::select` method:

https://github.com/glushkovds/phpclickhouse-laravel/blob/2009960f896851d1baa27422843a799644aeb6b1/src/Connection.php#L69-L75

I solved this one by just removing the `compileWheres` override, which means that the `prepareParameters` method is now only called once on the final query, which seems to fix everything in all the scenarios I've tested.

**Comment by glushkovds** [comment]
This happens because you are still using `\Illuminate\Database\Query\Builder`.

Check this:
```php
dd(get_class(DB::table('my-table')));
// you will see Illuminate\Database\Query\Builder
```

To fix this issue you should:
1. Upgrade this lib to the latest version v2.1.0
2. Add `'fix_default_query_builder' => true,` to your connection

Then you will see:
```php
dd(get_class(DB::table('my-table')));
// PhpClickHouseLaravel\Builder
```

**Comment by jessarcher** [comment]
Thanks again for the reply @glushkovds!

I understand that there are two builders and that the Tinderbox one solves the issue. But if I wanted to stay with the Illuminate Builder, I'm curious to know what would break with my approach in this PR?

**Comment by glushkovds** [comment]
You can run the tests and see: https://github.com/glushkovds/phpclickhouse-laravel/blob/master/docs/howto_run_local_test.md

Supporting both builders is a bad idea. Unfortunately they are not compatible.

**Comment by jessarcher** [comment]
Thanks again, @glushkovds!

I ran the tests and everything is passing on my end. I found an issue with my PR yesterday afternoon which I've already pushed a fix for, so perhaps that's why it was failing when you tried.

image

I agree that two builders isn't ideal and I totally understand if you only want to support the Tinderbox because of its extra features. I already have a lot of code using the Illuminate builder and haven't noticed any missing features for my use case, so I was trying to stick with it for now. I'm also probably a bit biased in wanting to stick with the Illuminate one because I work for Laravel :laughing: 

I totally understand if you want to close this PR! Thanks for your time and great work on this package!

On a separate note, you might be interested to know that I gave a presentation about ClickHouse during Laracon US a few weeks ago and I mentioned your package briefly in one of my slides towards the end:

image

https://www.youtube.com/watch?v=_jjvaFWWKqg

**Comment by glushkovds** [comment]
@jessarcher excellent presentation!

As for using the Illuminate builder:

It's my mistake that I didn't see that the library produces different builders in different cases. For example, the model produces Tinderbox, and `DB::table` produces Illuminate.  
This is bad, better to use one builder, so as not to think every time you use it, which builder you now have at hand.  
When I creating the library, I decided that it was easier to use a ready-made builder than to adapt builder from Laravel.

Let's try adding some parameter to the connection that will switch the default builder to the Illuminate one?
Can you help me support two builders at once?

As for your PR - I've already made and checked the changes based on it: now it should work with Illuminate too: https://github.com/glushkovds/phpclickhouse-laravel/commit/2efca916eee39f29e0cab74ba4d1b7b7991d2e66

I think many people who using this lib use Illuminate builder as you too. Now we need to decide what to do next and release it.

**Comment by jessarcher** [comment]
Thanks, @glushkovds! The changes look good. The only issue I can think of is if someone runs a query containing a literal `?` symbol. For example, using the alias syntax for ternaries (`cond ? then : else`) mentioned in [the docs](https://clickhouse.com/docs/en/sql-reference/functions/conditional-functions). Or perhaps a raw query with a `?` symbol in a string somewhere. The previous placeholder was a bit more unique.

Interesting point about the scenarios where you'd get different builders. I don't have any ClickHouse-based models in my project because I'm only running aggregate queries and never returning individual records, so I never noticed there were different builders!

Am I correct that the Illuminate builder uses `smi2/phpClickHouse` and the Tinkerbox builder uses `the-tinderbox/clickhouse-php-client`? I suppose it's not a big issue to have two clients because ClickHouse uses a HTTP API so the clients presumably don't open a long-lived connection like they would for something like MySQL.

I'm happy to help supporting both builders. I don't know much about the Tinderbox builder so I'll probably be more helpful with the Illuminate one. A config setting to set the default builder sounds like great idea! Is there anything specifically you'd like me to do?

**Comment by glushkovds** [comment]
@jessarcher Yes, correct remark about the `?` sign.  
I merged your changes, thank you for your work.

A question not on this topic: how do you insert data into the ClickHouse? For insertion I use the ClickHouse Buffer engine. But it is not very fast. Now I have written a small library where Redis is used as a buffer. But now I see a better solution - to use Kafka, I want this library to integrate with the library for insertion via Kafka.

To support for the Illuminate builder: I will create a new PR.

Regarding your participation: can I mention you in new possible issues with the Illuminate builder?

**Comment by jessarcher** [comment]
> A question not on this topic: how do you insert data into the ClickHouse? For insertion I use the ClickHouse Buffer engine. But it is not very fast. Now I have written a small library where Redis is used as a buffer. But now I see a better solution - to use Kafka, I want this library to integrate with the library for insertion via Kafka.

For my current use case, I'm not inserting anything into ClickHouse via PHP in the main application code - the application only reads data. The only time I insert into ClickHouse from PHP is in the test suite and database seeders, and I've found the `insertAssocBulk`, `insertFiles` and `streamWrite` methods from the `\ClickHouseDB\Client` class (`smi2/phpclickhouse`) to be pretty fast. E.g:

```php
DB::connection('clickhouse')->getClient()->insertAssocBulk($table, $rows);
```

For production, I've been playing with [ClickPipes](https://clickhouse.com/cloud/clickpipes) which is part of ClickHouse Cloud. It can automatically ingest data from Kafka, Kinesis, and other sources. When setting it up, you configure how the stream data maps to the table columns, but I don't think you can do much transformation, so the stream data needs to be pretty clean.

An interesting workaround to apply some transformation is to use [ephemeral columns](https://clickhouse.com/docs/en/sql-reference/statements/create/table#ephemeral) that another column can reference in its default expression. You can also ingest into a table configured with the ["Null" table engine](https://clickhouse.com/docs/en/engines/table-engines/special/null) and then create a materialized view to insert the data into another table with any required transformations, aggregations, etc.

> To support for the Illuminate builder: I will create a new PR.
> 
> Regarding your participation: can I mention you in new possible issues with the Illuminate builder?

Sure!

**Pull request merged**
